version : '3.5'

services:
  main:
    build:
      context: ./main   #代表上下文当前目录
      dockerfile: Dockerfile     #DockerFile的文件名字
    volumes:
      - ./main/CTFFiles:/CTFFiles
      - ./main/CTFImages:/CTFImages
      - ./main/CertKey:/CertKey
      - ./main/log:/var/log/springboot
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    networks:
      default:
      internal:
  db:
    image: mysql:8.0.15
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=marsdb
      - MYSQL_PASSWORD=marsdb
      - MYSQL_DATABASE=marsdb
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql/marsdb.sql:/docker-entrypoint-initdb.d/marsdb.sql
    privileged: true 
    networks:
      internal:
  nginx:    # 服务名称  用户自定义
    image: nginx:latest
    ports:
      - 7991:80     # 暴露端口
    volumes:      # 挂载
      - ./nginx/html:/usr/share/nginx/html  #挂载：前面是挂载到哪儿，后面是nginx得配置目录
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    privileged: true  # 这个必须要，解决nginx的文件调用的权限问题
    depends_on:
      - main
    networks:
      default:
      internal:
  redis:
    image: redis:7.0.4
    expose:
      - "6379"
    restart: always
    networks:
      internal:

networks:
    default:
    internal:
        internal: true
